[package]
name = "snaike"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }  # WASM-compatible RNG
rand = "0.8"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3", features = ["console"] }

[lib]
crate-type = ["cdylib"]
